// ui/src/app/layout/navbar/navbar.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'tfa-navbar',
  templateUrl: './navbar.component.html',
  styleUrl: './navbar.component.scss',
})
export class NavbarComponent {}

<div class="navbar bg-primary text-primary-content">
  <div class="navbar-start">
    <button class="btn btn-ghost" routerLink="/">
      <img src="/assets/logo.svg" width="40" />
    </button>
  </div>

  <div class="navbar-center hidden lg:flex">
    <a class="nav-item" routerLink="/meals" routerLinkActive="nav-item-active">
      <fa-icon icon="utensils" />
      <span>Meals</span>
    </a>
    <a class="nav-item" routerLink="/training-plans" routerLinkActive="nav-item-active">
      <fa-icon icon="table-list" />
      <span>Training Plans</span>
    </a>
    <a class="nav-item" routerLink="/excercises" routerLinkActive="nav-item-active">
      <fa-icon icon="dumbbell" />
      <span>Excercises</span>
    </a>
  </div>

  <ul class="navbar-end">
    <div class="dropdown dropdown-end lg:hidden">
      <div tabindex="0" role="button" class="nav-item">
        <fa-icon icon="bars" size="lg" />
      </div>
      <ul tabindex="0" class="menu dropdown-content z-[1] p-2 shadow bg-primary rounded-box w-94 mt-4">
        <li>
          <a class="nav-item" routerLink="/meals" routerLinkActive="nav-item-active">
            <fa-icon icon="utensils" />
            <span>Meals</span>
          </a>
        </li>
        <li>
          <a class="nav-item" routerLink="/training-plans" routerLinkActive="nav-item-active">
            <fa-icon icon="table-list" />
            <span>Training Plans</span>
          </a>
        </li>
        <li>
          <a class="nav-item" routerLink="/excercises" routerLinkActive="nav-item-active">
            <fa-icon icon="dumbbell" />
            <span>Excercises</span>
          </a>
        </li>
      </ul>
    </div>
  </ul>
</div>

// src/lib/Navbar.svelte
<script>
	import Icon from './Icon.svelte';
</script>

<div class="navbar">
	<a href="/" class="text-lg font-bold">The Fit App</a>

	<div class="dropdown dropdown-end">
		<div tabindex="0" role="button" class="btn btn-ghost rounded-btn">
			<Icon icon="bars" />
		</div>
		<ul class="menu dropdown-content">
			<li>
				<a href="/exercises">
					<Icon icon="dumbbell" />
					<span>Exercises</span>
				</a>
			</li>
			<li>
				<a href="/training-plans">
					<Icon icon="list" />
					<span>Training Plans</span>
				</a>
			</li>
		</ul>
	</div>
</div>

<style lang="postcss">
	.dropdown-content {
		width: calc(100vw - 1rem);

		@apply mt-4 p-2 z-[1] rounded-box shadow-2xl bg-base-100;
	}

	.navbar {
		display: flex;
		justify-content: space-between;
	}
</style>
