// ui/src/app/modules/training-plans/components/exercise-card/exercise-card.component.ts
import { Component, input } from '@angular/core';
import { Exercise } from 'src/app/modules/excercises/models/exercise.model';

@Component({
  selector: 'tfa-exercise-card',
  templateUrl: './exercise-card.component.html',
  styleUrl: './exercise-card.component.scss'
})
export class ExerciseCardComponent {
  exercise = input.required<Exercise>();
  series = input.required<number>();
  reps = input.required<number>();
}

<div class="base-card card-body h-full">
  <div class="actions">
    <a [routerLink]="['/exercises', exercise().id]" target="_blank" class="btn btn-sm btn-ghost">
      <fa-icon icon="up-right-from-square" />
    </a>
  </div>

  <figure class="p-3">
    @if (exercise().image) {
    <img class="rounded-xl" [src]="exercise().image" />
    } @else {
    <img class="rounded-xl" src="/assets/images/exercise-placeholder.webp" />
    }
  </figure>

  <div>
    <span class="card-title">{{ exercise().name }} - {{ series() }} x {{ reps() }}</span>
  </div>
</div>

// src/lib/exercises/components/ExerciseCard.svelte
<script lang="ts">
	import Icon from '$lib/Icon.svelte';
	import type { Exercise } from '../exercise.model';

	export let exercise: Exercise;
</script>

<div class="card">
	<div class="card-actions">
		<a href={`/exercises/${exercise.id}`}  class="btn btn-sm btn-ghost">
			<Icon icon="link-new-tab" />
		</a>
	</div>

	<figure>
		<img src={exercise.image} alt={exercise.name} />
	</figure>

	<div class="card-body">
		<h2 class="card-title">{exercise.name}</h2>
	</div>
</div>
