// ui/src/app/layout/navbar/navbar.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'tfa-navbar',
  templateUrl: './navbar.component.html',
  styleUrl: './navbar.component.scss',
})
export class NavbarComponent {}

<div class="navbar bg-primary text-primary-content">
  <div class="navbar-start">
    <button class="btn btn-ghost" routerLink="/">
      <img src="/assets/logo.svg" width="40" />
    </button>
  </div>

  <div class="navbar-center hidden lg:flex">
    <a class="nav-item" routerLink="/meals" routerLinkActive="nav-item-active">
      <fa-icon icon="utensils" />
      <span>Meals</span>
    </a>
    <a class="nav-item" routerLink="/training-plans" routerLinkActive="nav-item-active">
      <fa-icon icon="table-list" />
      <span>Training Plans</span>
    </a>
    <a class="nav-item" routerLink="/excercises" routerLinkActive="nav-item-active">
      <fa-icon icon="dumbbell" />
      <span>Excercises</span>
    </a>
  </div>

  <ul class="navbar-end">
    <div class="dropdown dropdown-end lg:hidden">
      <div tabindex="0" role="button" class="nav-item">
        <fa-icon icon="bars" size="lg" />
      </div>
      <ul tabindex="0" class="menu dropdown-content z-[1] p-2 shadow bg-primary rounded-box w-94 mt-4">
        <li>
          <a class="nav-item" routerLink="/meals" routerLinkActive="nav-item-active">
            <fa-icon icon="utensils" />
            <span>Meals</span>
          </a>
        </li>
        <li>
          <a class="nav-item" routerLink="/training-plans" routerLinkActive="nav-item-active">
            <fa-icon icon="table-list" />
            <span>Training Plans</span>
          </a>
        </li>
        <li>
          <a class="nav-item" routerLink="/excercises" routerLinkActive="nav-item-active">
            <fa-icon icon="dumbbell" />
            <span>Excercises</span>
          </a>
        </li>
      </ul>
    </div>
  </ul>
</div>

// src/lib/ui/components/Navbar.svelte
<!-- svelte-ignore a11y-no-noninteractive-tabindex -->
<script>
	import Icon from '../../Icon.svelte';
</script>

<div class="navbar">
	<div class="nav-start">
		<a href="/" class="home-link">
			<Icon icon="heart-pulse" size="2x" />
			<span>The Fit App</span>
		</a>
	</div>

	<div class="nav-end">
		<div class="dropdown dropdown-end">
			<div tabindex="0" role="button" class="btn btn-ghost btn-circle">
				<Icon icon="bars" />
			</div>
			<ul
				tabindex="0"
				class="menu menu-sm dropdown-content bg-base-100 rounded-box z-[1] w-48 mt-3 p-2 shadow-2xl"
			>
				<li>
					<a href="/exercises">
						<Icon icon="dumbbell" size="sm" />
						<span>Exercises</span>
					</a>
				</li>
				<li>
					<a href="/training-plans">
						<Icon icon="list" size="sm" />
						<span>Training Plans</span>
					</a>
				</li>
			</ul>
		</div>
	</div>

	<div class="nav-end-lg">
		<a class="nav-item" href="/exercises">
			<Icon icon="dumbbell" size="sm" />
			<span>Exercises</span>
		</a>
			<a class="nav-item" href="/training-plans">
				<Icon icon="list" size="sm" />
				<span>Training Plans</span>
			</a>
	</div>

	
</div>

<style lang="postcss">
	.home-link {
		display: flex;
		align-items: center;

		@apply gap-3 text-lg font-bold;
	}

	.navbar {
		display: flex;
		justify-content: space-between;

		@apply bg-primary;
	}

	.nav-end {
		@apply md:hidden;
	}

	.nav-end-lg {
		@apply hidden md:flex gap-2;
	}

	.nav-item {
		@apply btn btn-secondary;
	}
</style>
